### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by ThatGuyCalledJesse** [newtoallofthis123/NoobPaste#6]
When visit the site it displays this message ``An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail``

**Comment by newtoallofthis123** [comment]
Yes @ThatGuyCalledJesse! I am sorry, but NoobPaste was hosted on the Heroku free program . There have been attempts to transfer to another site, but this is made difficult due to having a costly PostgreSQL database to it. Sorry. If you have any Heroku alternatives that are rather affordable, please reach out :) [Email](mailto:noobscience@duck.com)
